// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddcourseandenrollteacherstudentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addcourseandenrollteacherstudent() {
    driver.get("https://sandbox.moodledemo.net/");
    driver.manage().window().setSize(new Dimension(1294, 1400));
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("sandbox");
    driver.findElement(By.id("loginbtn")).click();
    driver.findElement(By.linkText("Site administration")).click();
    driver.findElement(By.linkText("Courses")).click();
    driver.findElement(By.linkText("Add a new course")).click();
    driver.findElement(By.id("id_fullname")).click();
    driver.findElement(By.id("id_fullname")).sendKeys("TestingSurvey");
    driver.findElement(By.id("id_shortname")).click();
    driver.findElement(By.id("id_saveandreturn")).click();
    driver.findElement(By.id("id_shortname")).sendKeys("TSY");
    driver.findElement(By.linkText("TestingSurvey")).click();
    driver.findElement(By.linkText("Participants")).click();
    driver.findElement(By.cssSelector("#enrolusersbutton-1 .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#enrolusersbutton-1 .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("form_autocomplete_input-1712332058318")).click();
    driver.findElement(By.id("form_autocomplete_input-1712332058318")).sendKeys("Sam Student");
    driver.findElement(By.cssSelector("#form_autocomplete_suggestions-1712332058318-0 span:nth-child(2)")).click();
    driver.findElement(By.id("yui_3_18_1_1_1712332058082_231")).click();
    driver.findElement(By.id("yui_3_18_1_1_1712332058082_288")).click();
    driver.findElement(By.id("yui_3_18_1_1_1712332058082_37")).click();
    driver.findElement(By.id("form_autocomplete_input-1712332058319")).click();
    driver.findElement(By.id("form_autocomplete_input-1712332058319")).click();
    driver.findElement(By.id("form_autocomplete_input-1712332058319")).sendKeys("Terri Teacher");
    driver.findElement(By.id("form_autocomplete_input-1712332058319")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("id_roletoassign")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_roletoassign"));
      dropdown.findElement(By.xpath("//option[. = 'Teacher']")).click();
    }
    driver.findElement(By.id("yui_3_18_1_1_1712332058082_453")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".modal-footer > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
